addons:
    apt:
        sources:
            - devian-sid
sudo: required
before_script:
    - sudo apt update
    - sudo apt install binutils-dev libasound2-dev libunwind-dev
language: rust
rust:
    - nightly
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - ./scripts/run-fuzzing-tests
