addons:
    apt:
        sources:
            - devian-sid
        packages:
            - binutils-dev
            - libasound2-dev
            - libunwind8-dev
            - libxxf86vm-dev
            - libxinerama-dev
            - libxinerama1
            - libxcursor-dev
            - libxcursor1
            - libglfw-dev
            - libosmesa6-dev
            - libxi-dev
            - libxrandr-dev
            - g++
sudo: false
before_script:
    - rustup default nightly-2019-09-13
    - rustup component add clippy
    - rustup component add rustfmt
language: rust
rust:
    - nightly
cache:
    directories:
    - $HOME/.cargo
before-cache:
    - rm -rf $HOME/.cargo/registry
env:
    - RUN_ON_TRAVIS=default
script:
  - export PATH="$PATH:/usr/bin"
  - travis_wait 50 xvfb-run --server-args="-screen 0 1920x1080x24" ./scripts/run-all --filter 'run-vulkan-validation|run-all-benchmarks|run-fuzzing-tests|crates/vxdraw'
