addons:
    apt:
        sources:
            - devian-sid
sudo: required
before_script:
    - sudo apt update
    - sudo apt install binutils-dev libasound2-dev libunwind8-dev g++
    - ln -s /usr/bin/g++ /usr/bin/c++
language: rust
rust:
    - nightly
script:
  - ./scripts/run-all
