sudo: required
before_script:
    - sudo apt update
    - sudo apt install binutils-devel libasound2-dev libunwind-devel/libunwind8-devel
language: rust
rust:
    - nightly
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - ./scripts/run-fuzzing-tests
