addons:
    apt:
        sources:
            - devian-sid
sudo: required
before_script:
    - sudo apt update
    - sudo apt install binutils-dev libasound2-dev libunwind8-dev g++
language: rust
rust:
    - nightly
script:
  - export PATH="$PATH:/usr/bin"
  - travis_wait ./scripts/run-all no-bench
