addons:
    apt:
        sources:
            - devian-sid
sudo: false
before_script:
    - sudo apt update
    - sudo apt install binutils-dev libasound2-dev libunwind8-dev g++
    - rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
language: rust
rust:
    - nightly
cache:
    directories:
    - $HOME/.cargo
before-cache:
    - rm -rf $HOME/.cargo/registry
script:
  - export PATH="$PATH:/usr/bin"
  - travis_wait 50 ./scripts/run-all --filter 'run-vulkan-validation|run-all-benchmarks|run-fuzzing-tests'
