[package]
name = "universe"
version = "0.3.0"
authors = ["Erlend Hofstad Langseth <3rlendhl@gmail.com>", "Kevin Robert Stravers <macocio@gmail.com>"]
edition = "2018"

[lib]
name = "universe"
path = "src/lib.rs"

[dependencies]
bincode = "1.0.1"
byteorder = "1.2.7"
clap = "2.32.0"
derive_more = "0.11.0"
failure = "0.1.1"
glium = "0.16.0"
honggfuzz = "0.5"
rand = "0.6.1"
serde = "1.0"
serde_derive = "1.0"
time = "0.1.4"
toml = "0.4.9"

[features]
default = []
dev = []

[profile.release]
debug = true

[profile.dev]
codegen-units = 4
