[package]
name = "universe"
version = "0.3.0"
authors = ["Erlend Hofstad Langseth <3rlendhl@gmail.com>", "Kevin Robert Stravers <macocio@gmail.com>"]

[dependencies]
tile_net = { git = "https://github.com/Ploppz/TileNet" }
tilenet_ren = { git = "https://github.com/Ploppz/tilenet-render"}
clippy = { version = "0.0", optional = true }
isatty = "0.1"
slog = { version = "1", features = ["max_level_trace", "release_max_level_trace"] }
slog-json = "1"
slog-scope = "0"
slog-stream = "1"
slog-term = "1"
time = "0"
glium = "0.15.0"
rand = "0"
clap = "2.19.3"
byteorder = "1.0.0"
bincode = "0.6.0"
rustc-serialize = "0.3"
num-traits = "*"
error-chain = "0.7.2"
specs = "0.9"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"

[features]
default = []
dev = ["clippy"]

[profile.release]
debug = true

[profile.dev]
codegen-units = 4
