[package]
name = "universe"
version = "0.3.0"
authors = ["Erlend Hofstad Langseth <3rlendhl@gmail.com>", "Kevin Robert Stravers <macocio@gmail.com>"]

[dependencies]
bgjk = "0"
clippy = { version = "0.0", optional = true }
tile_net = { git = "https://github.com/BourgondAries/TileNet", branch = "polygon-state" }
tilenet_ren = { git = "https://github.com/Ploppz/tilenet-render", branch = "polygon-state"}
isatty = "0.1"
slog = { version = "1", features = ["max_level_trace", "release_max_level_trace"] }
slog-json = "1"
slog-scope = "0"
slog-stream = "1"
slog-term = "1"
time = "0"
glium = "0"
rand = "0"

[features]
default = []
dev = ["clippy"]

[profile.release]
debug = true
