[package]
name = "universe"
version = "0.2.0"
authors = ["Erlend Hofstad Langseth <3rlendhl@gmail.com>", "Kevin Robert Stravers <macocio@gmail.com>"]

[dependencies]
tile_net = "2"
tilenet_ren = { git = "https://github.com/Ploppz/tilenet-render" }
isatty = "0.1"
slog = { version = "1", features = ["max_level_trace", "release_max_level_warn"] }
slog-json = "1"
slog-scope = "0"
slog-stream = "1"
slog-term = "1"
time = "0"
glium = "*"
rand = "*"
