# Units are in pixels and seconds (actually atm probably not - the ECS system does not know the delta time)
[player]
hori_acc = 1000
jump_duration = 0.05
jump_delay = 0.5
jump_acc = 8000

[world]
width = 700
height = 700
gravity = 1000
air_fri = [0.98, 0.99]
ground_fri = 0.5

[srv]
tps = 60
