[package]
name = "input"
version = "0.3.0"
authors = ["Erlend Hofstad Langseth <3rlendhl@gmail.com>", "Kevin Robert Stravers <macocio@gmail.com>"]
edition = "2018"

[lib]
name = "input"
path = "lib.rs"

[dependencies]
winit = "0.18.0"
