#! /usr/bin/env bash

set -Eeuo pipefail

FILE="$(basename $0)"
DIR="${0%$FILE}"

cd "$DIR.."
DIR="${DIR%/*}"
DIR="${DIR##*/}"


export CARGO_TARGET_DIR=_build/hfuzz/hfuzz_target
export HFUZZ_WORKSPACE=_build/hfuzz/hfuzz_workspace

if [ -d _build/hfuzz ]; then
    rm -r _build/hfuzz
fi

mkdir -p _build/hfuzz

cargo install --force honggfuzz >& "_build/hfuzz/install"

builderr=0
for TARGET in tests/fuzz/src/bin/*; do
    FILE="$(basename $TARGET)"
    FILE="${FILE%.*}"
    if [ -d "hfuzz_input/$FILE/" ]; then
        HFUZZ_INPUT_ARGS="-f ${target%/*}/$FILE/input"
    fi

    cd tests/fuzz/
    set +e
    HFUZZ_BUILD_ARGS="" \
    HFUZZ_RUN_ARGS="-N1000000 --exit_upon_crash ${HFUZZ_INPUT_ARGS:+-v} ${HFUZZ_INPUT_ARGS:-}" \
    cargo hfuzz run "$FILE" >& ../../_build/hfuzz/"$FILE"
    if [ "$?" -ne 0 ]; then
        builderr="$((builderr + 1))"
    fi
    set -e
    cd ../../
    HFUZZ_INPUT_ARGS=
done

if [ "$builderr" -gt 0 ]; then
    echo "$builderr fuzzing tests failed building"
fi

found=0
for TARGET in tests/fuzz/*; do
    FILE="$(basename $TARGET)"
    FILE="${FILE%.*}"
    report="hfuzz_workspace/$FILE/HONGGFUZZ.REPORT.TXT"
    if [ -f "$report" ]; then
        cat "$report"
        for CASE in "hfuzz_workspace/$FILE/SIG"*; do
            cat "$CASE" | xxd -p
        done
        found="$((found + 1))"
    fi
done

if [ "$found" -gt 0 ]; then
    echo "$found fuzzing tests found errors"
    exit 1
fi

if [ "$builderr" -gt 0 ]; then
    exit 1
fi

echo "All fuzzing tests passed"
