#! /usr/bin/env bash

set -Eeuo pipefail

FILE="$(basename $0)"
DIR="${0%$FILE}"

cd "$DIR.."
DIR="${DIR%/*}"
DIR="${DIR##*/}"

if [ $# -gt 0 ]; then
    filter="$1"
else
    filter=""
fi

failures=0
for SCRIPT in "$DIR"/*; do
    if [ "$SCRIPT" = "$DIR/$FILE" ]; then
        continue
    fi
    if ! [ -z "$filter" ]; then
        if echo "$SCRIPT" | grep -P "$filter" >& /dev/null; then
            continue
        fi
    fi
    echo "Running: $SCRIPT"
    set +e
    time ./"$SCRIPT" |& sed 's/^/\t/g'
    if [ "$?" -ne 0 ]; then
        failures="$((failures + 1))"
    fi
    set -e
done

if [ "$failures" -ne 0 ]; then
    echo "$failures scripts failed"
    exit 1
else
    echo "All scripts passed"
fi
