#! /usr/bin/env bash

set -Eeuo pipefail

FILE="$(basename $0)"
DIR="${0%$FILE}"

cd "$DIR.."
DIR="${DIR%/*}"
DIR="${DIR##*/}"

mkdir -p _build/crates


(
    has_failed=0

    cd crates/vxdraw

    set +e
    cargo test --verbose --all >& _build/vulkan.test_result
    if [ "$?" -ne 0 ]; then
        echo "FAIL: vulkan-validation"
        cat _build/vulkan.test_result
        has_failed=1
    else
        echo "PASS: vulkan-validation"
    fi
    set -e

    if [ -z "${VULKAN_SDK:-}" ]; then
        echo "VULKAN_SDK is not set, to continue this test, please source the setup-env.sh provided by the SDK"
        exit "$has_failed"
    fi

    set +e
    VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation cargo test --release --quiet >& _build/vulkan.test_result.validation
    set -e

    if grep 'ERROR / SPEC' _build/vulkan.test_result.validation >& /dev/null; then
        echo "FAIL: vulkan-validation (VK_LAYER_LUNARG_standard_validation)"
        cat _build/vulkan.test_result.validation
        has_failed=1
    else
        echo "PASS: vulkan-validation (VK_LAYER_LUNARG_standard_validation)"
    fi

    exit "$has_failed"
)
