#! /usr/bin/env bash

set -Eeuo pipefail

FILE="$(basename $0)"
DIR="${0%$FILE}"

cd "$DIR.."
DIR="${DIR%/*}"
DIR="${DIR##*/}"

mkdir -p _build/crates

has_failed=0

set +e
cargo test --verbose --all >& _build/main.test_result
if [ "$?" -ne 0 ]; then
    echo "FAIL: main"
    cat _build/main.test_result
    has_failed=1
else
    echo "PASS: main"
fi
set -e

for library in crates/*; do
    if [ -f "$library"/.test-ignore ]; then
        echo "IGNORE: $library"
        continue
    fi
    cd "$library"
    set +e
    cargo test --verbose --all >& ../../_build/"$library.test_result"
    if [ "$?" -ne 0 ]; then
        echo "FAIL: $library"
        cat ../../_build/"$library.test_result"
        has_failed=1
    else
        echo "PASS: $library"
    fi
    set -e
    cd ../..
done

exit "$has_failed"
